version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bogcha_oshxona
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=bogcha_oshxona
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1234
      - REDIS_URL=redis://redis:6379/0

  celery:
    build: .
    command:
      - celery
      - "-A"
      - "config"
      - "worker"
      - "-l"
      - "info"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=bogcha_oshxona
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1234
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command:
      - celery
      - "-A"
      - "config"
      - "beat"
      - "-l"
      - "info"
      - "--scheduler"
      - "django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=bogcha_oshxona
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1234
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
